@url =  https://x5krb1cbe6.execute-api.us-east-1.amazonaws.com/dev

###
GET {{url}}/quotes


###
POST {{url}}/subscribe  
Content-Type: application/json

{
   "email": "gluzman.nir@gmail.com"
}

###
POST {{url}}/static-mailer
Content-Type: application/json

{
   "email": "gluzman.nir@gmail.com",
   "name": "nir",
   "message": "please subscribe me"
}

###
GET {{url}}/get-subscribers

###
POST {{url}}/send-email